// Mock data for the dashboard
export const memberData = {
  name: "Rahul Sharma",
  memberId: "TFG-2024-001",
  plan: "Elite",
  joinDate: "2024-01-15",
  expiryDate: "2025-01-15",
  trainer: "Vikram Singh",
  avatar: "/avatars/member.jpg",
  stats: {
    currentStreak: 12,
    longestStreak: 28,
    totalWorkouts: 156,
    caloriesBurned: 45600,
  },
  attendance: [
    { date: "2024-12-01", present: true },
    { date: "2024-12-02", present: true },
    { date: "2024-12-03", present: false },
    { date: "2024-12-04", present: true },
    { date: "2024-12-05", present: true },
    { date: "2024-12-06", present: true },
    { date: "2024-12-07", present: false },
  ],
  weeklyCalories: [
    { day: "Mon", calories: 450 },
    { day: "Tue", calories: 520 },
    { day: "Wed", calories: 380 },
    { day: "Thu", calories: 600 },
    { day: "Fri", calories: 480 },
    { day: "Sat", calories: 720 },
    { day: "Sun", calories: 0 },
  ],
  progressData: [
    { month: "Jul", weight: 85, muscle: 32, fat: 22 },
    { month: "Aug", weight: 83, muscle: 33, fat: 20 },
    { month: "Sep", weight: 81, muscle: 34, fat: 18 },
    { month: "Oct", weight: 79, muscle: 35, fat: 16 },
    { month: "Nov", weight: 78, muscle: 36, fat: 15 },
    { month: "Dec", weight: 76, muscle: 37, fat: 14 },
  ],
  todayWorkout: {
    name: "Upper Body Strength",
    exercises: [
      { name: "Bench Press", sets: 4, reps: 12, weight: "60kg" },
      { name: "Incline Dumbbell Press", sets: 3, reps: 10, weight: "20kg" },
      { name: "Cable Flyes", sets: 3, reps: 15, weight: "15kg" },
      { name: "Shoulder Press", sets: 4, reps: 10, weight: "40kg" },
      { name: "Lateral Raises", sets: 3, reps: 12, weight: "10kg" },
      { name: "Tricep Pushdowns", sets: 3, reps: 15, weight: "25kg" },
    ],
  },
  notifications: [
    { id: 1, message: "New workout plan assigned by Vikram", time: "2 hours ago", read: false },
    { id: 2, message: "Your membership expires in 30 days", time: "1 day ago", read: false },
    { id: 3, message: "Congratulations on 10-day streak!", time: "2 days ago", read: true },
  ],
}

export const exerciseLibrary = [
  {
    id: 1,
    name: "Barbell Bench Press",
    category: "Chest",
    difficulty: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/rT7DgCr-3pg",
    thumbnail: "/exercises/bench-press.jpg",
    description: "Primary chest exercise targeting pectorals, front deltoids, and triceps.",
  },
  {
    id: 2,
    name: "Deadlift",
    category: "Back",
    difficulty: "Advanced",
    videoUrl: "https://www.youtube.com/embed/op9kVnSso6Q",
    thumbnail: "/exercises/deadlift.jpg",
    description: "Compound movement targeting posterior chain including back, glutes, and hamstrings.",
  },
  {
    id: 3,
    name: "Squat",
    category: "Legs",
    difficulty: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/ultWZbUMPL8",
    thumbnail: "/exercises/squat.jpg",
    description: "King of leg exercises, targeting quads, glutes, and core stability.",
  },
  {
    id: 4,
    name: "Pull-ups",
    category: "Back",
    difficulty: "Intermediate",
    videoUrl: "https://www.youtube.com/embed/eGo4IYlbE5g",
    thumbnail: "/exercises/pullups.jpg",
    description: "Bodyweight exercise for lats, biceps, and overall back development.",
  },
  {
    id: 5,
    name: "Shoulder Press",
    category: "Shoulders",
    difficulty: "Beginner",
    videoUrl: "https://www.youtube.com/embed/qEwKCR5JCog",
    thumbnail: "/exercises/shoulder-press.jpg",
    description: "Overhead pressing movement for deltoid development.",
  },
  {
    id: 6,
    name: "Bicep Curls",
    category: "Arms",
    difficulty: "Beginner",
    videoUrl: "https://www.youtube.com/embed/ykJmrZ5v0Oo",
    thumbnail: "/exercises/bicep-curl.jpg",
    description: "Isolation exercise for bicep peak and arm size.",
  },
]

export const motivationalQuotes = [
  { quote: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { quote: "Your body can stand almost anything. It's your mind you have to convince.", author: "Unknown" },
  { quote: "Strength does not come from the body. It comes from the will.", author: "Unknown" },
  { quote: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
]

export const adminData = {
  gymName: "Titan Fitness Gym",
  totalMembers: 847,
  activeMembers: 712,
  newMembersThisMonth: 43,
  revenue: {
    thisMonth: 1250000,
    lastMonth: 1180000,
    growth: 5.9,
  },
  attendance: {
    today: 156,
    average: 142,
    peak: 198,
  },
  membershipBreakdown: [
    { plan: "Starter", count: 234, percentage: 28 },
    { plan: "Pro", count: 389, percentage: 46 },
    { plan: "Elite", count: 224, percentage: 26 },
  ],
  recentPayments: [
    { id: 1, member: "Priya Patel", amount: 4999, plan: "Pro", date: "2024-12-15", status: "completed" },
    { id: 2, member: "Amit Kumar", amount: 7999, plan: "Elite", date: "2024-12-15", status: "completed" },
    { id: 3, member: "Sneha Reddy", amount: 2499, plan: "Starter", date: "2024-12-14", status: "completed" },
    { id: 4, member: "Raj Malhotra", amount: 4999, plan: "Pro", date: "2024-12-14", status: "pending" },
    { id: 5, member: "Ananya Singh", amount: 7999, plan: "Elite", date: "2024-12-13", status: "completed" },
  ],
  trainers: [
    { id: 1, name: "Vikram Singh", specialization: "Strength Training", members: 45, rating: 4.9, status: "active" },
    { id: 2, name: "Priya Sharma", specialization: "Yoga & Flexibility", members: 38, rating: 4.8, status: "active" },
    { id: 3, name: "Arjun Patel", specialization: "CrossFit", members: 32, rating: 4.7, status: "active" },
    { id: 4, name: "Neha Gupta", specialization: "Nutrition", members: 28, rating: 4.9, status: "on-leave" },
  ],
  weeklyAttendance: [
    { day: "Mon", members: 145 },
    { day: "Tue", members: 162 },
    { day: "Wed", members: 138 },
    { day: "Thu", members: 155 },
    { day: "Fri", members: 171 },
    { day: "Sat", members: 198 },
    { day: "Sun", members: 89 },
  ],
  monthlyRevenue: [
    { month: "Jul", revenue: 980000 },
    { month: "Aug", revenue: 1050000 },
    { month: "Sep", revenue: 1120000 },
    { month: "Oct", revenue: 1080000 },
    { month: "Nov", revenue: 1180000 },
    { month: "Dec", revenue: 1250000 },
  ],
  recentMembers: [
    { id: 1, name: "Karan Mehta", plan: "Elite", joinDate: "2024-12-15", phone: "+91 98765 43210" },
    { id: 2, name: "Divya Joshi", plan: "Pro", joinDate: "2024-12-14", phone: "+91 87654 32109" },
    { id: 3, name: "Rohit Verma", plan: "Starter", joinDate: "2024-12-13", phone: "+91 76543 21098" },
    { id: 4, name: "Isha Kapoor", plan: "Pro", joinDate: "2024-12-12", phone: "+91 65432 10987" },
  ],
  announcements: [
    { id: 1, title: "New Year Fitness Challenge", content: "Join our 30-day transformation challenge starting Jan 1st!", date: "2024-12-15", priority: "high" },
    { id: 2, title: "Holiday Hours", content: "Gym will operate 6 AM - 6 PM from Dec 25-31", date: "2024-12-14", priority: "medium" },
    { id: 3, title: "New Equipment Arrival", content: "New cable machines and treadmills arriving next week", date: "2024-12-10", priority: "low" },
  ],
}

export const chatMessages = [
  { id: 1, sender: "trainer", name: "Vikram Singh", message: "Great progress on your deadlifts yesterday!", time: "10:30 AM", avatar: "/trainers/vikram.jpg" },
  { id: 2, sender: "member", name: "You", message: "Thanks! I finally hit 100kg for 5 reps", time: "10:32 AM" },
  { id: 3, sender: "trainer", name: "Vikram Singh", message: "Excellent! Let's aim for 110kg next month. I've updated your workout plan.", time: "10:35 AM", avatar: "/trainers/vikram.jpg" },
  { id: 4, sender: "member", name: "You", message: "Sounds good! Should I increase protein intake?", time: "10:38 AM" },
  { id: 5, sender: "trainer", name: "Vikram Singh", message: "Yes, aim for 2g per kg bodyweight. I'll send you a meal plan.", time: "10:40 AM", avatar: "/trainers/vikram.jpg" },
]
